//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEEA_BO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LUIS-PC\\SQLSERVER;Initial Catalog=SIGEEA_BD;Integrated Security=True")]
        public string SIGEEA_BDConnectionString {
            get {
                return ((string)(this["SIGEEA_BDConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ROBERTOAF\\ROBERTO;Initial Catalog=SIGEEA_BD;Integrated Security=True")]
        public string SIGEEA_BDConnectionString1 {
            get {
                return ((string)(this["SIGEEA_BDConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Luis-PC\\SQLEXPRESS;Initial Catalog=SIGEEA_BD;Integrated Security=True" +
            "")]
        public string SIGEEA_BDConnectionString2 {
            get {
                return ((string)(this["SIGEEA_BDConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC-PC\\ROBERTO;Initial Catalog=SIGEEA_BD;Integrated Security=True")]
        public string SIGEEA_BDConnectionString3 {
            get {
                return ((string)(this["SIGEEA_BDConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LUIS-PC\\SQLEXPRESS;Initial Catalog=SIGEEA_BD;Integrated Security=True" +
            "")]
        public string SIGEEA_BDConnectionString4 {
            get {
                return ((string)(this["SIGEEA_BDConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-UG5K51J\\SQLEXPRESS;Initial Catalog=SIGEEA_BD;Integrated Secur" +
            "ity=True")]
        public string SIGEEA_BDConnectionString5 {
            get {
                return ((string)(this["SIGEEA_BDConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JINTAN\\SQLEXPRESS;Initial Catalog=SIGEEA_BD;User ID=sa")]
        public string SIGEEA_BDConnectionString6 {
            get {
                return ((string)(this["SIGEEA_BDConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JINTAN\\SQLEXPRESS;Initial Catalog=SIGEEA_BD;Persist Security Info=Tru" +
            "e;User ID=sa")]
        public string SIGEEA_BDConnectionString7 {
            get {
                return ((string)(this["SIGEEA_BDConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JINTAN\\SQLEXPRESS;Initial Catalog=SIGEEA_BD;Persist Security Info=Tru" +
            "e;User ID=sa;Password=1234")]
        public string SIGEEA_BDConnectionString8 {
            get {
                return ((string)(this["SIGEEA_BDConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JINTAN\\SQLEXPRESS;Initial Catalog=SIGEEA_BD;Integrated Security=True")]
        public string SIGEEA_BDConnectionString9 {
            get {
                return ((string)(this["SIGEEA_BDConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-NJFF1DG\\SQLEXPRESS;Initial Catalog=SIGEEA_BD;Integrated Secur" +
            "ity=True")]
        public string SIGEEA_BDConnectionString10 {
            get {
                return ((string)(this["SIGEEA_BDConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-B08M2J3\\SQLEXPRESS;Initial Catalog=SIGEEA_BD;Integrated Secur" +
            "ity=True")]
        public string SIGEEA_BDConnectionString11 {
            get {
                return ((string)(this["SIGEEA_BDConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-UNGN8I1\\SQLEXPRESS;Initial Catalog=SIGEEA_BD;Integrated Secur" +
            "ity=True")]
        public string SIGEEA_BDConnectionString12 {
            get {
                return ((string)(this["SIGEEA_BDConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A5H5HL0;Initial Catalog=SIGEEA_BD;Integrated Security=True")]
        public string SIGEEA_BDConnectionString13 {
            get {
                return ((string)(this["SIGEEA_BDConnectionString13"]));
            }
        }
    }
}
